version: '3.8'

services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile  
    ports:
      - "8080:8080"  
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app  
