version: '3.8'

services:
    app:
        container_name: tier_seperator
        build:
            context: ./tier_seperator
            dockerfile: Dockerfile
        ports:
            - '8081:8081'
        environment:
            - PYTHONDONTWRITEBYTECODE=1
            - PYTHONUNBUFFERED=1
        env_file: .env
        volumes:
            - ./tier_seperator:/app
