version: '3.8'

services:
  app:
    build:
      context: .  
      dockerfile: ./tier_seperator/Dockerfile  
    ports:
      - "8081:8081"  
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app  
